kafka:
  config:
    bootstrap-address: 172.20.20.10:9094,172.20.20.20:9094,172.20.20.30:9094
    topic-name: my-topic
#    topic-name: topic-test-3 # tiga yg bener config nya
    numPartitions: 2
    replicationFactor: 3
